apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
labels:
  app: hello
spec:
  strategy:
    type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: samour/movieapi2
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
        name: hello

---
apiVersion: v1
kind: Service
metadata:
  name: hello
labels:
  app: hello
spec:
  ports:
  - port: 3000
    targetPort: 3000
selector:
  app: hello
  tier: hello
type: LoadBalancer